import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/db";

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const session = await auth();
  if (!session?.user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { id } = await params;
  const userId = (session.user as { id: string }).id;
  const project = await prisma.project.findFirst({
    where: { id, userId },
    include: {
      messages: { orderBy: { createdAt: "asc" } },
    },
  });

  if (!project) {
    return NextResponse.json({ error: "Not found" }, { status: 404 });
  }

  const agentLabels: Record<string, string> = {
    ANALYST: "AI Analyst — Validation",
    BUILDER: "AI Builder — MVP",
    GROWTH: "AI Growth — Market Testing",
    INVESTOR: "AI Investor — Fundraising",
  };

  let markdown = `# ${project.name}\n\n`;
  markdown += `> ${project.description}\n\n`;
  markdown += `**Phase:** ${project.phase}\n`;
  if (project.score !== null) {
    markdown += `**Validation Score:** ${project.score}/100\n`;
  }
  if (project.pricingTier) {
    markdown += `**Pricing Tier:** ${project.pricingTier === "HIGH_POTENTIAL" ? "High Potential" : "Complex Build"}\n`;
  }
  markdown += `**Created:** ${project.createdAt.toISOString().split("T")[0]}\n\n`;
  markdown += `---\n\n`;

  const messagesByAgent = new Map<string, typeof project.messages>();
  for (const msg of project.messages) {
    const existing = messagesByAgent.get(msg.agent) || [];
    existing.push(msg);
    messagesByAgent.set(msg.agent, existing);
  }

  for (const [agent, messages] of messagesByAgent) {
    markdown += `## ${agentLabels[agent] || agent}\n\n`;
    for (const msg of messages) {
      if (msg.role === "user") {
        markdown += `**You:** ${msg.content}\n\n`;
      } else {
        markdown += `${msg.content}\n\n`;
      }
    }
    markdown += `---\n\n`;
  }

  markdown += `\n*Generated by PONYX — The AI Operating System for Startups*\n`;

  const filename = `${project.name.replace(/[^a-zA-Z0-9]/g, "-").toLowerCase()}-report.md`;

  return new NextResponse(markdown, {
    headers: {
      "Content-Type": "text/markdown; charset=utf-8",
      "Content-Disposition": `attachment; filename="${filename}"`,
    },
  });
}
